name: Deployment Workflow
on:
  push:
    branches:
      - seun007B

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: "create function"
      run: |
        aws lambda create-function --function-name testfunction --zip-file fileb://code.py --runtime python3.9 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/seunxxrole --handler testfunction.handler    
    
    - name: "checks if this works"
      run: |
        echo "Everything works fine"  
    - name: 'Convert to zip format'
      run: |
        zip -j test.zip ./code.py 

        aws lambda update-function-code --function-name testfuction --zip-file fileb://test.zip    
