name: Deployment Workflow
on:
  push:
    branches:
      - seun007B

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
     
    - name: Convert to Zip Format
      run: zip -j test.zip ./code.py    

    - name: Create Lambda Function
      run: |
        aws lambda create-function --function-name testfunction --zip-file fileb://test.zip --runtime python3.9 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/seunxxrole --handler testfunction.handler

    - name: Check if Everything Works
      run: echo "Everything works fine"    
