name: Deployment Workflow
on:
  push:
    branches:
      - seun007B

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
     
    - name: Convert to Zip Format
      run: zip -j test.zip ./code.py    

    - name: Create Lambda Role
      run: |
        aws iam create-role --role-name bestrole --assume-role-policy-document file://sample.json
    
    - name: wait for role creation
      run: sleep 10  
      
    - name: "Create policy"
      run: |
        aws iam create-policy --policy-name bestpolicy --policy-document file://policy.json

    - name: wait for policy creation
      run: sleep 30

    - name: Attach policy to role
      run: |
        aws iam attach-role-policy --role-name bestrole --policy-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/bestpolicy

    - name: wait for policy attachment
      run: sleep 10

    - name: Create Lambda Function
      run: |
        aws lambda create-function --function-name Wfunction --zip-file fileb://test.zip --runtime python3.9 --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/bestrole --handler Wfunction.handler

    - name: Wait for Lambda Creation
      run: sleep 10
  
    
    - name: Update Lambda Function Code
      run: |
        aws lambda update-function-code --function-name Wfunction --zip-file fileb://test.zip
              
    - name: Check if Everything Works
      run: echo "Everything works fine"    
